# Generated by Django 3.2.7 on 2021-09-30 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Maxsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=200)),
                ('chegirma', models.CharField(max_length=4)),
                ('rangi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online_shop.rang')),
                ('turi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online_shop.tur')),
            ],
        ),
    ]
