# Generated by Django 3.2.7 on 2021-10-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxsulotlar',
            name='rasm',
            field=models.ImageField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maxsulotlar',
            name='chegirma',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
