# Generated by Django 3.2.7 on 2021-10-06 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0003_auto_20211005_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chegirmalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=40)),
                ('narxi', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
                ('rasm', models.ImageField(upload_to='media/')),
                ('rangi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online_shop.rang')),
                ('turi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online_shop.tur')),
            ],
        ),
    ]
