# Generated by Django 3.2.7 on 2021-10-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0004_chegirmalar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happy_clents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=40)),
                ('rasmi', models.ImageField(upload_to='media/')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
