# Generated by Django 3.2.7 on 2021-10-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0006_auto_20211009_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.EmailField(max_length=200)),
            ],
        ),
    ]
